---
title: "Picking up from Cameron's Book TS Project"
author: "thank you Cameron Stewart"
date: "11/15/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Load Packages

```{r}
library(RCurl)
library(tswge)
library(tidyverse)
library(lubridate)
library(tseries)
library(stats)
library(vars)
```

# Bring in peak finding function

```{r}
#Can also be used to find valleys if you put -x in instead of x for realization
find_peaks <- function (x, m = 3){
    shape <- diff(sign(diff(x, na.pad = FALSE)))
    pks <- sapply(which(shape < 0), FUN = function(i){
       z <- i - m + 1
       z <- ifelse(z > 0, z, 1)
       w <- i + m + 1
       w <- ifelse(w < length(x), w, length(x))
       if(all(x[c(z : i, (i + 2) : w)] <= x[i + 1])) return(i + 1) else return(numeric(0))
    })
     pks <- unlist(pks)
     pks
}
```

# Bring in valley finding function

```{r}
find_valleys <- function (x, m = 3){
    x=-x
    shape <- diff(sign(diff(x, na.pad = FALSE)))
    pks <- sapply(which(shape < 0), FUN = function(i){
       z <- i - m + 1
       z <- ifelse(z > 0, z, 1)
       w <- i + m + 1
       w <- ifelse(w < length(x), w, length(x))
       if(all(x[c(z : i, (i + 2) : w)] <= x[i + 1])) return(i + 1) else return(numeric(0))
    })
     pks <- unlist(pks)
     pks
}
```

# Bring in rolling window ASE function

```{r}
Rolling_Window_ASE = function(series, trainingSize, horizon = 1, s = 0, d = 0, phis = 0, thetas = 0)
{
ASEHolder = numeric()

for( i in 1:(length(series)-(trainingSize + horizon) + 1))
{
  
  forecasts = fore.aruma.wge(series[i:(i+(trainingSize-1))],phi = phis, theta = thetas, s = s, d = d,n.ahead = horizon)
  
  ASE = mean((series[(trainingSize+i):(trainingSize+ i + (horizon) - 1)] - forecasts$f)^2)
         
  ASEHolder[i] = ASE

}

ASEHolder
hist(ASEHolder)
WindowedASE = mean(ASEHolder)

print("The Summary Statistics for the Rolling Window ASE Are:")
print(summary(ASEHolder))
print(paste("The Rolling Window ASE is: ",WindowedASE))
return(WindowedASE)
}
```



# Read in the data set data types

```{r}

# 
#covid <- read.csv(file.choose(), header = TRUE, sep = ",")
#read.csv(text=getURL("https://raw.githubusercontent.com/C-Stewart-GH/Time_Series_Project/main/Raw_Data_Files/merged_data.csv"))
#covid$Date=mdy(covid$Date)
#str(covid)
#summary(covid)
# 
#cases= read.csv(file.choose(), header = TRUE, sep = ",")
# #read.csv(text=getURL("https://raw.githubusercontent.com/C-Stewart-GH/Time_Series_Project/main/Raw_Data_Files/Texas%20COVID-19%20Case%20Count%20Data%20by%20County.csv"))
# cases$Date=mdy(cases$Date)
# cases$Case.Count=c(NA,diff(cases$Case.Count))
# cases=cases[2:length(cases$Date),]
# str(cases)
#cases = cases$Case.Count

```

```{r}
mergedD <- read.csv(file.choose(), header = TRUE, sep = ",")

```



# Look at the crosssorrelations, it appears there is a strong lag -2 component

```{r}

merged <- mergedD[,c('Date','case_count','tests_taken', 'vaccine_doses_administered')]
a <- mergedD$case_count[1:395]
b <- mergedD$tests_taken[1:395]
c <- mergedD$vaccine_doses_administered[1:395]

actuals <- mergedD$case_count[396:416]
ccf(a,b)
X = cbind(a,b)

plot(mergedD$case_count, type = "l")
plot(mergedD$tests_taken, type = "l", col="Red")
plot(mergedD$vaccine_doses_administered, type = "l", col="Blue")

```

#select lag 1 since it has the highest AIC

```{r}
VARselect(X)
lsfit = VAR(X, p=7, type = "const", season = NULL, exogen = NULL)

```

```{r}
preds_SHORT = predict(lsfit, n.ahead = 7)
preds_SHORT

preds_LONG = predict(lsfit, n.ahead = 21)
preds_LONG

z <- preds_SHORT$fcst$a[0:7,1]

zz <- preds_LONG$fcst$a[0:21,1]


plot(merged$case_count, type = "l")
lines(seq(400,406,1), z, type = "l", col = "red")
lines(seq(400,420,1), zz, type = "l", col = "blue")



```

```{r}

actuals_short = actuals[0:7]
z
ASE_short = mean((actuals_short-z)^2)
RMSE_short = sqrt(ASE_short) 
RMSE_short

ASE_long = mean((actuals-zz)^2)
ASE_long
RMSE_LONG = sqrt(ASE_long) 
RMSE_LONG

```


```{r}
library(nnfor)

cases = merged$case_count
tests = merged$tests_taken
vaccines = merged$vaccine_doses_administered
mobility = mergedD$parks_percent_change_from_baseline

covidData = ts(cases[1:395])
covidX = data.frame(testsTS = ts(tests), vaccinesTS = ts(vaccines))
set.seed(2)
fitCOVID = mlp(covidData,xreg = covidX)
fcstCOVID= forecast(fitCOVID,h=21,xreg = covidX)

plot(fitCOVID)
plot(fcstCOVID)

plot(fcstCOVID$mean,type="l",ylim=c(-10000,15000),lwd=5, main="MLP Predict Cases per Tests & Vaccines")
for (i in 1:20){
    lines(fcstCOVID$all.mean[,i],col = "grey",type = "l")
}
lines(seq(396,416), tail(cases,21),type = "l",col="blue",lwd=5)


plot(merged$case_count, type = "l")
lines(seq(400,420),fcstCOVID$mean,col = "blue")


ASE_DEEP_LONG = mean((tail(cases,21) - fcstCOVID$mean)^2)
ASE_DEEP_LONG
RMSE_DEEP_LONG = sqrt(ASE_DEEP_LONG)
RMSE_DEEP_LONG
plot(fitCOVID)

covidDataShort = ts(cases[1:409])
fitCOVID_short = mlp(covidDataShort,xreg = covidX)
fcstCOVID_short= forecast(fitCOVID_short,h=7,xreg = covidX)
plot(tail(merged$case_count,21), type = "l", ylim=c(-2000,10000))
#plot(merged$case_count, type = "l", main=ASE_long)
lines(seq(410,416),fcstCOVID_short$mean,col = "blue")

ASE_DEEP_SHORT = mean((tail(cases,7) - fcstCOVID_short$mean)^2)
ASE_DEEP_SHORT
RMSE_DEEP_SHORT = sqrt(ASE_DEEP_SHORT)
RMSE_DEEP_SHORT

```

What happens when we add another regressor?

```{r}
covidData = ts(cases[1:395])
covidXX = data.frame(testsTS = ts(tests), vaccinesTS = ts(vaccines), rec_mobility= ts(mobility))
set.seed(2)
fitCOVIDXX = mlp(covidData,xreg = covidXX)

fcstCOVIDXX= forecast(fitCOVIDXX,h=21,xreg = covidXX)


plot(fcstCOVIDXX$mean,type="l",ylim=c(-10000,15000),lwd=5, main="MLP Predict Cases per Vaccines, Tests and Park Mobility")
for (i in 1:20){
    lines(fcstCOVIDXX$all.mean[,i],col = "grey",type = "l")
}
lines(seq(396,416), tail(cases,21),type = "l",col="blue",lwd=5)


plot(tail(merged$case_count,21), type = "l", ylim=c(-2000,10000))
lines(seq(1,21),fcstCOVID$mean,col = "blue")
lines(seq(1,21),fcstCOVIDXX$mean,col = "red")
lines(seq(1,21), zz, type = "l", col = "green")

ASE_DEEP_LONG_XX = mean((tail(cases,21) - fcstCOVIDXX$mean)^2)
ASE_DEEP_LONG_XX
RMSE_DEEP_LONG_XX = sqrt(ASE_DEEP_LONG_XX)
RMSE_DEEP_LONG_XX
plot(fitCOVIDXX)
fitCOVIDXX

ASE_DEEP_SHORT_XX = mean((tail(cases,21)[1:7] - fcstCOVIDXX$mean[1:7])^2)
ASE_DEEP_SHORT_XX
RMSE_DEEP_SHORT_XX = sqrt(ASE_DEEP_SHORT_XX)
RMSE_DEEP_SHORT_XX



```


What happens when we add OTHER regressor?

```{r}

parks = mergedD$parks_percent_change_from_baseline

covidData = ts(cases[1:395])
covidXX = data.frame(testsTS = ts(tests), vaccinesTS = ts(vaccines), rec_mobility= ts(mobility))
set.seed(2)
fitCOVIDXX = mlp(covidData,xreg = covidXX)
fcstCOVIDXX= forecast(fitCOVIDXX,h=21,xreg = covidXX)
plot(fcstCOVIDXX)

plot(tail(merged$case_count,21), type = "l", ylim=c(-2000,10000))
lines(seq(1,21),fcstCOVID$mean,col = "blue")
lines(seq(1,21),fcstCOVIDXX$mean,col = "red")
lines(seq(1,21), zz, type = "l", col = "green")

ASE_DEEP_LONG_XX = mean((tail(cases,21) - fcstCOVIDXX$mean)^2)
ASE_DEEP_LONG_XX
RMSE_DEEP_LONG_XX = sqrt(ASE_DEEP_LONG_XX)
RMSE_DEEP_LONG_XX
```


```{r}

parks = mergedD$parks_percent_change_from_baseline
retail = mergedD$retail_and_recreation_percent_change_from_baseline

covidData = ts(cases[1:395,2])
covidXXX = data.frame(testsTS = ts(tests), vaccinesTS = ts(vaccines), rec_mobility= ts(mobility), retail_mobility= ts(retail))
fitCOVIDXXX = mlp(covidData,xreg = covidXX)
fcstCOVIDXXX= forecast(fitCOVIDXX,h=21,xreg = covidXX)

plot(tail(merged$case_count,21), type = "l", ylim=c(-2000,10000))
lines(seq(1,21),fcstCOVID$mean,col = "blue")
lines(seq(1,21),fcstCOVIDXX$mean,col = "red")
lines(seq(1,21), zz, type = "l", col = "green")
lines(seq(1,21),fcstCOVIDXXX$mean,col = "purple")


ASE_DEEP_LONG_XXX = mean((tail(cases,21) - fcstCOVIDXXX$mean)^2)
ASE_DEEP_LONG_XXX
RMSE_DEEP_LONG_XXX = sqrt(ASE_DEEP_LONG_XXX)
RMSE_DEEP_LONG_XXX

```


